models.py
from extensions import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password = db.Column(db.String(150), nullable=False)

forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=3, max=80)])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Register')


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')

app.py
from flask import Flask
from extensions import db
from routes import app as app_routes

def create_app():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///users.db'
    app.config['SECRET_KEY'] = 'some_secret_key'
    db.init_app(app)
    app.register_blueprint(app_routes)

    with app.app_context():
        db.create_all()

    return app


if __name__ == '__main__':
    app = create_app()
    app.run(debug=False)

auth.py
from flask import session, flash, redirect, url_for
from werkzeug.security import check_password_hash
from functools import wraps
from models import User


def authenticate(username, password):
    user = User.query.filter_by(username=username).first()
    if user and check_password_hash(user.password, password):
        return user
    return None

def login_required(f):
    @wraps(f)
    def decorated_func(*args, **kwargs):
        if 'user_id' not in session:
            flash('Please login first!', 'warning')
            return redirect(url_for('app.login'))
        return f(*args, **kwargs)
    return decorated_func

routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, session
from werkzeug.security import generate_password_hash
from extensions import db
from models import User
from forms import RegistrationForm, LoginForm
from auth import login_required, authenticate


app = Blueprint('app', __name__)

@app.route('/')
def home():
    return render_template('home.html')

@app.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        username = form.username.data      
        password = form.password.data
        hashed_password = generate_password_hash(password)
        user = User(username=username, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Registration successful! Log in now!', 'success')
        return redirect(url_for('app.login'))
    return render_template('register.html', form=form)


@app.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = authenticate(form.username.data, form.password.data)
        if user:
            session['user_id'] = user.id
            flash('Login successful!', 'success')
            return redirect(url_for('app.dashboard'))
        flash('Ivalid credentials!', 'danger')
    return render_template('login.html', form=form)

@app.route('/dashboard')
@login_required
def dashboard():
    user_id = session.get('user_id')
    user = User.query.get(user_id)
    return render_template('dashboard.html', username=user.username)


@app.route('/logout')
def logout():
    session.pop('user_id', None)
    flash('Logged out', 'info')
    return redirect(url_for('app.home'))


@app.route('/stats')
def stats():
    count = User.query.count()
    return render_template('stats.html', user_count=count)

templates/dashboard.html
<!DOCTYPE html>
<html>
    <head>
        <title>Dashboard</title>
    </head>
    <body>
        <h1>Welcome {{username}} to ur dashboard</h1>
        <a href="{{ url_for('app.logout') }}">Logout</a>
        <a href="{{ url_for('app.stats') }}">Users</a>
    </body>
</html>

templates/home.html
<!DOCTYPE html>
<html>
    <head>
        <title>Home</title>
    </head>
    <body>
        <h1>Welcome to the app</h1>
        <a href="{{ url_for('app.login') }}">Login</a>
        <a href="{{ url_for('app.register') }}">Register</a>
    </body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>Login</title>
    </head>
    <body>
        <h1>Login</h1>
        <form method="POST">
            {{ form.hidden_tag() }}
            {{ form.username.label }} {{ form.username() }}<br>
            {{ form.password.label }} {{ form.password() }}<br>
            {{ form.submit() }}
        </form>
    </body>
</html>

templates/register.html
<!DOCTYPE html>
<html>
    <head>
        <title>Register</title>
    </head>
    <body>
        <h1>Register</h1>
        <form method="POST">
            {{ form.hidden_tag() }}
            {{ form.username.label }} {{ form.username() }}<br>
            {{ form.password.label }} {{ form.password() }}<br>
            {{ form.submit() }}
        </form>
    </body>
</html>

templates/stats.html
<!DOCTYPE html>
<html>
    <head>
        <title>How many users registered</title>
    </head>
    <body>
        <h1>Total registreted users: {{ user_count }}</h1>
        <a href = "{{ url_for('app.home') }}">Home</a>
    </body>
</html>